🧑‍💻 cool logins
SlavaAndreievvvv/login pull request #1
Opened 2022-11-11 19:29 UTC by SlavaAndreievvvv

2022-11-14 11:33 UTC, a1exalexander requested changes
- [ ] виправ класси, усі кнопки і инпути повинні бути також блоками, оскільки їх можливо перевикористати (те, що я вказав у коментарах)

- [ ] жирність тексту в інпуті повинна бути 600
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/40409129/201649103-12e9cc4b-f0b8-498b-8e29-89923fa1e2b1.png">

- [ ] жирність і видступ зліва щось не співпадає з дизайном
<img width="1554" alt="image" src="https://user-images.githubusercontent.com/40409129/201649598-8b24285d-cb1c-4ebc-baab-b9fdfa63c35f.png">

- [ ] немає валідації (в дизайні в плейсхолдерах написано, що мінімальна калькість символів для паролю - 8)

2022-11-14 11:33 UTC, a1exalexander commented on login-page-second/style.css
> +  height: 100vh;
краще задавай `min-height: 100vh;` на всяк випадок

2022-11-14 11:33 UTC, a1exalexander commented on login-page-second/style.css
> +}
`input` завжди блок, тому стилі треба задавати через класс `.input {}`, а стилі, що відповідають за розташування і відступи, треба задавати до елементів, ане блоків, тут все вірно `.login__input {}`,

2022-11-14 11:33 UTC, a1exalexander commented on login-page-second/style.css
> +}
усі стилі окрім `margin-bottom` треба застосовувати до блока .`button {}`

2022-11-14 13:52 UTC, SlavaAndreievvvv commented on login-page-second/style.css
> +}
Дякую за зауваження! Все виправив.

2022-11-16 12:51 UTC, a1exalexander approved these changes

2022-11-16 12:51 UTC, merged